[package]
name = "airstation"
version = "0.1.0"
authors = ["Alexandre Peyroux <alex@px.io>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33.0"
csv = "1.1.1"
serde = { version = "1.0.101", features = ["derive"] }
serial = "0.4.0"